### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Pchao93** [Pchao93/goodPlays#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by dobrynin** [comment]
I'll sign off on this, but I would also highly recommend that you invest a little more time into styling. Not to say that it looks bad, but with a little more work it could look great.

**Comment by Pchao93** [comment]
Is this referring to the session styling? Or the main styling of the site?
In either case, pointers are appreciated :)

**Comment by dobrynin** [comment]
Upon comparison with Twitch, I see that what you've made is actually a pretty faithful clone. That said, I'm not a _huge_ fan of their styling. Some things to consider.

1. Hover effects on the buttons
2. Adding a "goodPlays" logo at the top of the session form.
3. Making the overlay opaque (or even some interesting background?) rather than transparent gray.
4. Adding a bit more color to the form.
5. Using `:hover { cursor: pointer }` for the logout button. You could also add a transition to the dropdown to make a smoother "accordion" effect.
